# nginx proxy address - http://172.17.0.1:8103

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  xbackbone:
    image: xbackbone/xbackbone:latest
    container_name: xbackbone-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - xbackbone
    ports:
      - "8103:8103"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/xbackbone:/config
      - ./volumes/data/xbackbone:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8103"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  xbackbone:
    external: false
