# nginx proxy address - http://172.17.0.1:8103

name: xbackbone
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  xbackbone:
    image: pe46dro/xbackbone-docker:latest
    pull_policy: always
    container_name: xbackbone-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - xbackbone
    ports:
      - "172.17.0.1:8103:80"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      APP_NAME: ${APP_NAME:-XBackBone}
      URL: http://${BASE_HOST_NAME:-$HOSTNAME}:8103
    volumes:
      - ./volumes/config/xbackbone:/app/config
      - ./volumes/data/xbackbone:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  xbackbone:
    name: xbackbone
    external: false
